### ISSUE TITLE
CSS Checklist: Layouts

### ISSUE THREAD

**Issue by samw0627** [samw0627/sp23-cse110-lab3#11]
[FlexboxLinks](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)  : allow your elements to lay themselves out automatically 
apply flex to the display property
- [ ] **Must have more than two children** within the element that is using flexbox. 
- [ ] Must use minimum **three** of the flexbox related attributes

[Grid](https://css-tricks.com/snippets/css/complete-guide-grid/) : instantiate a grid for your layouts
apply grid to the display property
- [ ] Must have more than **two children** within the element that is using the grid. 
- [ ] Must use a minimum of **three of the grid related attributes**
