### ISSUE TITLE
CSS Checklist: Selectors

### ISSUE THREAD

**Issue by samw0627** [samw0627/sp23-cse110-lab3#14]
- [ ] Class Selector (`.class`)
- [ ] ID Selector (`#id`)
- [ ] Universal Selector (`*`)
- [ ] Element Selector (`element`) 
- [ ] Attribute Selector (e.g. [`attribute=foo`])     
- [ ] Pseudo-class Selector (e.g. `p:hover`)
- [ ] Selector List (`element, element`)                   /* select multiple elements */
- [ ] Descendant Combinator (`element element`)
- [ ] Child Combinator (`element > element`)
- [ ] General sibling combinator (`element ~ element`)
- [ ] Adjacent sibling combinator (`element + element`)
- [ ] Combining Two Selectors (`element.class`)
