### ISSUE TITLE
CSS Checklist: Colors

### ISSUE THREAD

**Issue by samw0627** [samw0627/sp23-cse110-lab3#2]
- [ ] rgb(r, g, b) or rgba(r, g, b, a)     /* red, green, blue, alpha values */
- [ ] #FFF or #FFFFFF                    /* hex codes */
- [ ] hsl(h, s, l) or hsla(h, s, l, a)       /* hue, saturation, lightness, alpha values */
- [ ] Color name (i.e ‘orange’)
