### ISSUE TITLE
CSS Checklist: Box Models

### ISSUE THREAD

**Issue by samw0627** [samw0627/sp23-cse110-lab3#5]
**Box Models**(“long” and “short” refer to longhand and shorthand syntax and should give the same results. They’re simply different ways to declare your style rules, use at least one of each syntax. You must use both long and short hand notations for each of the following: margin, padding, border) 
**Margin**     _/* spacing between html elements */_
- [ ] `Long (margin-top, margin-bottom, margin-left, margin-right)`
- [ ] `Short (margin: <top> <right> <bottom> <left>)`
- [ ] `Auto margins: margin: auto`

**Padding**     _/* spacing within html elements */_
- [ ] `Long (padding-top, padding-bottom, padding-left, padding-right)`
- [ ] `Short (padding: <top> <right> <bottom> <left>)`

**Borders**   _/* borders around html elements, hint: apply borders before testing out padding and margin to better understand the difference between the two */_
- [ ] `border-style`
- [ ] `border-color`
- [ ] `border-width`
- [ ] `border-radius`
